### ISSUE TITLE
Some workflows work now, then not anymore.

### ISSUE THREAD

**Issue by yuricarvalhop** [eubr-bigsea/juicer#85]
As shown in LSL, some workflows work randomly
![screenshot_20171101_161822](https://user-images.githubusercontent.com/20230045/32290203-6e527272-bf20-11e7-930b-a9db16f0701c.png)
![screenshot_20171101_161840](https://user-images.githubusercontent.com/20230045/32290204-6e6ec670-bf20-11e7-9e5a-2200a8fecaaa.png)

**Comment by waltersf** [comment]
Apparently, there is a problem with Spark when we submit the workflow and it splits the execution for the same dataframe. A workaround was implemented in the code.
