### ISSUE TITLE
Implement Kaplan-meier

### ISSUE THREAD

**Issue by michelboaventura** [eubr-bigsea/juicer#93]
We need to run the Kaplan–Meier estimator on lemonade. I've created the above code which receives a dictionary and three key names needed for the algorithm. It outputs a dictionary where de keys are the possible variable values and the valures are the result.

```python
from lifelines import KaplanMeierFitter

def kaplan_meier(data, y_name, x_name, time_name):
    kmf = KaplanMeierFitter()
    out = {}

    E = (data[y_name] == 1)

    for fact in set(data[x_name]):
        y = (data[x_name] == fact)
        kmf.fit(data[time_name][y], event_observed = E[y])
        out[fact] = kmf.survival_function_.values.flatten()

    return out
```

**Comment by michelboaventura** [comment]
The operation need to have three parameters: x, y and time variables, which are part of the dataset.

**Comment by waltersf** [comment]
PR #97 implemented this. Being tested.
