### ISSUE TITLE
Summary Statistics isn't working

### ISSUE THREAD

**Issue by mgonc** [eubr-bigsea/juicer#94]
I am getting the error below when using summary statistics operation
![image](https://user-images.githubusercontent.com/6419508/35629736-88c5b5da-0686-11e8-947e-33209b176445.png)

![image](https://user-images.githubusercontent.com/6419508/35629806-b7233da8-0686-11e8-86a6-266ea0cacb15.png)

**Comment by gpavelar** [comment]
What is the workflow number?

**Comment by gpavelar** [comment]
I created a new workflow (number 292) with the same operations that you. At Summary statistics Operation, you need to put "all" into field to really consider every attributes from data reader. After that, I got another error "Invalid or missing parameters: range() step argument must not be zero"

**Comment by waltersf** [comment]
PR #99 fixed this. Under testing.

**Comment by waltersf** [comment]
Fixed
