### ISSUE TITLE
Implementation of Feature Scaling (Normalization) Operation

### ISSUE THREAD

**Issue by pedrobernardina** [eubr-bigsea/juicer#95]
Normalization is an important tool to data scientists, in order to work with values of different orders of magnitude altogether. 

Different techniques can be seen on this [Wikipedia article.](https://en.wikipedia.org/wiki/Feature_scaling).

**Comment by gpavelar** [comment]
Maybe the operation that you searching is on "Machine Learning Operations - Feature Extraction - {Max-min Scale, Max-abs Scalar or Standard Scaler}. I think these operations should be in ETL Operations.
